[theme]
primaryColor = "#2e86ab"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1a1f24"
textColor = "#fafafa"

[server]
maxUploadSize = 10
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = false